export const FORMULARIO_TICKET ="FORMULARIO_TICKET";
export const OBTENER_TICKETS ="OBTENER_TICKETS";
export const AGREGAR_TICKETS ="AGREGAR_TICKETS";
export const ACTUALIZAR_TICKET ="ACTUALIZAR_TICKET";
export const VALIDAR_FORMULARIO ="VALIDAR_FORMULARIO";
export const TICKET_ACTUAL ="TICKET_ACTUAL";
export const ELIMINAR_TICKET ="ELIMINAR_TICKET";
export const TICKET_ERROR="TICKET_ERROR";
export const ACTUALIZA_STATUS="ACTUALIZA_STATUS";



export const MOSTRAR_ALERTA="MOSTRAR_ALERTA"
export const OCULTAR_ALERTA="OCULTAR_ALERTA"

export const REGISTRO_EXITOSO="REGISTRO_EXITOSO"
export const REGISTRO_ERROR="REGISTRO_ERROR"
export const OBTENER_USUARIO="OBTENER_USUARIO"
export const LOGIN_EXITOSO="LOGIN_EXITOSO"
export const LOGIN_ERROR="LOGIN_ERROR"
export const CERRAR_SESION="CERRAR_SESION"


export const PRODUCTOS_PROYECTO ="PRODUCTOS_PROYECTO";
export const AGREGAR_PRODUCTO ="AGREGAR_PRODUCTO";
export const VALIDAR_PRODUCTO ="VALIDAR_PRODUCTO";
export const ELIMINAR_PRODUCTO ="ELIMINAR_PRODUCTO";
export const PRODUCTO_ACTUAL="PRODUCTO_ACTUAL";
export const ACTUALIZAR_PRODUCTO="ACTUALIZAR_PRODUCTO"
export const LIMPIAR_PRODUCTO="LIMPIAR_PRODUCTO"
export const PRODUCTO_ERROR="PRODUCTO_ERROR";